Issue #40:http protocol is hardcoded in the URL
umputun/secrets pull request #41
Opened 2024-08-20 15:53 UTC by oneils

- moved hardcoded protocol to an argument

2024-09-07 18:09 UTC, umputun requested changes
Thanks for the PR. It looks fine, but not an easy one to review as, in addition to the expected (small) change, it also changed other things, like public/private visibility of some structs and fields.

It would be nice if you could split it into two commits: one with the actual protocol change and another with everything else you have improved.

2024-09-07 22:08 UTC, oneils commented
Sure, no problem. I'll do it

2024-09-15 19:45 UTC, oneils commented
@umputun  please take a look at #43
After the #43 is merged, I'll rebase this branch with master.

2024-09-16 02:42 UTC, umputun approved these changes

2024-09-16 02:42 UTC, umputun approved these changes

2024-09-16 02:42 UTC, merged